server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1    #采样率 介于0 - 1 之间  1表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: 106710

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.cloud.common.entity      #所有Entity别名类所在包


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
     # defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    #lease-renewal-interval-in-seconds: 1
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实例删除
    #lease-expiration-duration-in-seconds: 2
